source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_dependencies
  pod 'LibraryTemplate', :path => '../'
end

target 'DevApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  shared_dependencies
end


target 'DevAppTests' do
  shared_dependencies
end
